### ISSUE TITLE
GT mask for tier3 training data unavailable

### ISSUE THREAD

**Issue by bcstyle** [ethanweber/xview2#4]
Thanks for the great work! Looks like the current code requires training image quads and GT mask quads both available in the `train_images_quad/` and `train_and_tier3_GT_masks_quad/` directories. However the xView2 dataset tier3 training data doesn't have the target mask, only json labels. The README in this repo indicate you trained on both tier1 and tier3, so just wondering how does it manage to get tier3 masks (do you have a custom tool outside the notebook/ directory?) Thanks again.

**Comment by Feiyu-Chen-THU** [comment]
I have the same question, too @bcstyle . Also, I find that with only the tier1 data to train the authors' model, the results are not good, far from the results reported in the paper. Specifically, I built the dataset with **detectron2_repo/detectron2/data/datasets/builtin.py** and trained with the config **configs/xview/joint-11.yaml**. The loss values fluctuated around 0.92-0.95, and the results were like this:

'score': 0.46962265575037, 
'damage_f1': 0.3287440795190166, 
'localization_f1': 0.7983393336235279,
'damage_f1_no_damage': 0.8701416378348041, 
'damage_f1_minor_damage': 0.2684648232087288, 
'damage_f1_major_damage': 0.6044860448356402, 
'damage_f1_destroyed': 0.1773316790921047

obviously lower than what was reported in the paper. 
I wonder whether you have tried training with tier1 data and whether you got similar results. Also, I wonder if you have found some way to get the target mask of tier3 data. Thanks!

**Comment by ethanweber** [comment]
Hey @bcstyle and @Feiyu-Chen-THU, thank you for reaching out. Apologies for the delay in response. During the xView2 competition, I downloaded the preprocessed images from a third-party GitHub repo, if I'm remembering correctly. I'm contacting people from the deactivated discord to see if the data is still online somewhere. Unfortunately I deleted my three local copies when clearing space. Hopefully in a few days I'll have an answer on where to obtain `train_images_quad/` and `train_and_tier3_GT_masks_quad/`.

I believe I used to have a script to compute the target masks from the JSON data, before finding the preprocessed version online. Please give me a few days to reach out and find this data. If it's not online, you can use the code in the repo to convert to COCO format and use that with detectron2 or export the images from the COCO format to mask images, which can then be used with the current data loader. I recommend computing the full semantic images ahead of time.

@Feiyu-Chen-THU what steps did you perform to preprocess the data? I realize my documentation omits these steps, as it depends on the third-party download link. To your question about only using tier1 data, I can't recall only using this data. We used both tiers for everything. However, your results don't look too surprising.

In the case where I can't find the `train_and_tier3_GT_masks_quad` download link, the steps to reproduce the results are as follows:
- Put both tier1 and tier3 images in the same directory.
- Generate the GT segmentation masks and save those images in a new folder. (This can be done by parsing the JSON, creating an image, and exporting to PNG.)
- Run the script to split every image into "quads", which are the folders mentioned in `detectron2_repo/detectron2/data/datasets/builtin.py`.

Thanks for your patience, and apologies for the difficulties here. Happy to help where I can. Since the competition, there are also many coding design choices that could be improved when using `detectron2`. In particular, the model can be updated by simply importing `detectron2` as a module, creating a custom model module, and then using the config.yaml to define the network architecture.

**Comment by ethanweber** [comment]
Great, I found it! See https://github.com/DIUx-xView/xView2_baseline/releases and the link https://github.com/DIUx-xView/xView2_baseline/releases/download/v1.0/train_and_tier3_GT_masks.tar.gz at this URL. The xView2 team went through the work of preprocessing the images. Please let me know if you have more questions.

**Comment by Feiyu-Chen-THU** [comment]
Thanks for your kind help @ethanweber ! Now I've got the target masks of tier3! 
But I still have some questions about the training results. For the results with only tier1 data which I mentioned before, You asked me about my preprocessing steps. Particularly, I used the script **notebooks/NB_make_quad_folder.ipynb** to split the downloaded tier1 data (both the images and targets) into quads and then followed with **detectron2_repo/detectron2/data/datasets/builtin.py**, in which the data set is split into "train"(97%) and "val"(3%) as you set. The model was then trained with your training script and config. The F1 results I listed before were the results on the "val" set (rather than the test set of xview2). 
Now I've tried training with both tier1 and tier3 using all the same scripts mentioned above. It seemed that the loss and score stopped improving after about 20,000 iterations (I trained for 45000 iterations in total). However, I doubt whether the training had converged because the results were still not as good as reported in your paper. In particular, the loss fluctuated between 0.91~0.93, and the scores on "val" set were like: 

"score": 0.6642076421768593
"damage_f1": 0.6236810027942846
"localization_f1": 0.7587698007362004
"damage_f1_no_damage": 0.8593488372942543
"damage_f1_minor_damage": 0.43722925322840595
"damage_f1_major_damage": 0.7315219849449166
"damage_f1_destroyed": 0.6266717578883918

That's better than only using tier1 data. I then calculated the scores on xview2 test set  (also split into "quads") but unfortunately, the results seemed much worse:

"score": 0.39361882420262057    **(0.738 reported in the paper)**
"damage_f1": 0.342375332499506
"localization_f1": 0.5131869715098879
"damage_f1_no_damage": 0.549796752588373
"damage_f1_minor_damage": 0.2138389627464597
"damage_f1_major_damage": 0.3482850445293437
"damage_f1_destroyed": 0.4316593046578258

According to your paper, your training took roughly 6 hours to convergence with 4 NVIDIA 1080 TIs. It also took around 6 hours for the 20, 000 iterations in my training, but my GPU is 1 NVIDIA Quadro P5000. So I'm still not sure about the convergence of my training considering different training speeds between devices. It may be helpful if you have the iteration number information of your training! Also, I have no idea about the possible factors leading to the different scores between my training and your work. Do you have any ideas about this? Thanks again!

**Comment by ethanweber** [comment]
Hey @Feiyu-Chen-THU, thanks for working through these challenges.

For the paper, I believe we had much fewer iterations than the 20,000 iterations you mentioned. Looking at one of our submissions (`output_joint_11_model_0169999`), looks like 169999 may be the ballpark when using 1 GPU. Note that we did some experiments on 1 2080 TI, but we did most on 4 1080 TIs, as reported in the paper. The loss definitely fluctuated a lot when we were training models during the competition. After too long, the loss would drop to 0 due to mostly zero labels in the GT masks.

I'd take a look at the following lines in the .yaml config file:
```
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
```
We would scale these numbers proportionally depending on whether we were using 1 or 4 GPUs. With one, I think we used:
```
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
```
Maybe adjust your learning rate to see if fluctuation will go down, as this can be a sign of high learning rate. Also note that the iteration number will be modified the same scalar as batch size changes. A larger batch size, then fewer iterations to achieve the same result.

Also, you can have a look at [this portion of the code](https://github.com/ethanweber/detectron2/blob/01b32f630e2c8d57e19fcf8aae30553edd581ce7/detectron2/modeling/meta_arch/semantic_seg.py#L198) and the file where the model is being used. Maybe play around with the loss, but I'd only do this after getting results more similar to what we report.

You could also increase the validation set size for debugging. We kept it very small to maximize performance on the leaderboard.

Good luck! Sorry it's been a challenge so far!

**Comment by Feiyu-Chen-THU** [comment]
Hey @ethanweber , I think I've found the main problem!

There is a problem within `metrics/xview2_metrics.py` used for calculating scores. In particular, in line 197-203:

```Python
197    def get_path_handlers(self):
198            self.path_handlers = []
199            for path in self.targ_dir.glob('*.png'):
200               geography, img_id, pre_post_type, disaster_or_localization, quad = path.name.rstrip('.png').split('_')
201               assert pre_post_type in ['pre', 'post'], f"type must have 'pre' or 'post' in filename, got {path}"
202               if pre_post_type == 'pre': # localization or damage is fine here
203                   self.path_handlers.append(PathHandler(self.pred_dir, self.targ_dir, img_id, quad))
```

Note the arguements passed to **PathHandler** in the line 203, which includes the paths, 'img_id' and 'quad'. Then I paid attention to the initialization function of **PathHandler** class. In line 41-49: 

```Python
41    temp = glob.glob(os.path.join(pred_dir, "*{}_pre_disaster_{}.png".format(img_id, quad)))
42    self.lp = temp[0] if len(temp) > 0 else None # localization prediction
43    temp = glob.glob(os.path.join(pred_dir, "*{}_post_disaster_{}.png".format(img_id, quad)))
44    self.dp = temp[0] if len(temp) > 0 else None # damage prediction
45    temp = glob.glob(os.path.join(targ_dir, "*{}_pre_disaster_{}.png".format(img_id, quad)))
46    self.lt = temp[0] if len(temp) > 0 else None # localization target
47    temp = glob.glob(os.path.join(targ_dir, "*{}_post_disaster_{}.png".format(img_id, quad)))
48    self.dt = temp[0] if len(temp) > 0 else None # damage target
49    self.paths = (self.lp, self.dp, self.lt, self.dt)
```

The problem is that, there are some groups of images with the same `img_id` and `quad`, for example, ```guatemala-volcano_00000005_post_disaster_tl.png``` and ```hurricane-florence_00000005_post_disaster_tl.png```. In this case, when using arguments 'img_id' and 'quad' in line 203, the list 'temp' in line 41 (43, 45 and 47) may have more than one elements.  Note that in line 42 (same in 44, 46 and 48), ```temp[0]``` is used, whose initial intention may be transforming the datatype from 'list' to 'str'. However, this means that the score calculating will only be executed on the first element of the list 'temp'. Thus the validation set (or test set) is not fully used. 

To solve this, I use the variable 'geography' in line 200 to get the unique image. Specifically, I changed line 203 into
```Python
self.path_handlers.append(PathHandler(self.pred_dir, self.targ_dir, geography, img_id, quad))
```
and the line 41 (same for 43, 45, 47) was changed into
```Python
temp = glob.glob(os.path.join(pred_dir, "{}_{}_pre_disaster_{}.png".format(geography, img_id, quad)))
```

I then recalculated the scores on the test set, with the same trained model mentioned in my last comment. Then I got:
```
'score': 0.7132209689110607 
'damage_f1': 0.6572387548628302
'localization_f1': 0.8438461350235985
'damage_f1_no_damage': 0.8963012442019946
'damage_f1_minor_damage': 0.42283840420816987
'damage_f1_major_damage': 0.714247630098062
'damage_f1_destroyed': 0.82964281355662}
```
very close to the results reported in your paper! Maybe further adjustment on the training config can improve it. 

Thank you very much for your help! I will pay continuous attention to xview2 challenge as well as other machine learning applications on emergency management and safety science.

**Comment by ethanweber** [comment]
Hey @Feiyu-Chen-THU, this is great! Thanks so much for pointing this out and finding this error. By the way, if you like ML for applications on emergency management, you might be interested in checking out a new dataset myself and colleagues just published at http://incidentsdataset.csail.mit.edu/ (project page) and https://github.com/ethanweber/IncidentsDataset (the code). If you're interested in the data, just let me know! It's an exciting time to work on ML for humanitarian aid. :)

**Comment by bcstyle** [comment]
Thank you @ethanweber and @Feiyu-Chen-THU ! I ended up converting the json labels with COCO format and export them as png mask, which is also one approach you suggested @ethanweber , but great to see there is an official mask. (I noticed that the COCO approach will result in mask with 3-9% difference in segmented areas compared to tier1 GT mask officially provided. Haven't got a chance to compare with this tier3 mask). Also happy to see this thread help facilitate discussion with @Feiyu-Chen-THU 

The Incidents Dataset is very interesting and will be sure to check out. Thank you!

**Comment by ethanweber** [comment]
I noticed the difference with the COCO approach too, which is part of the reason I went with the official masks download. I doubt it will change performance much, but it's good to look into. Thanks for all the insights on this thread!

**Comment by zyp-zhangyuping** [comment]
> 我也有同样的问题@bcstyle。另外，我发现只用tier1数据来训练作者的模型，结果并不好，与论文中报道的结果相差甚远。具体来说，我使用**detectron2_repo/detectron2/data/datasets/builtin.py 构建数据集**，并使用配置**configs/xview/joint-11.yaml 进行训练**。损失值在0.92-0.95左右波动，结果是这样的：
> 
> '得分'：0.46962265575037，
> 'damage_f1'：0.3287440795190166，
> 'localization_f1'：0.7983393336235279，
> 'damage_f1_no_damage'：0.8701416378348041，
> 'damage_f1_minor_damage'：0.2684648232087288，
> 'damage_f1_major_damage'：0.6044860448356402，
> 'damage_f1_destroyed'：0.1773316790921047
> 
> 明显低于论文中的报道。
> 我想知道您是否尝试过使用 tier1 数据进行训练，是否得到了类似的结果。另外，我想知道您是否找到了某种方法来获取tier3数据的目标掩码。谢谢！

**Comment by zyp-zhangyuping** [comment]
Hello, I am a college student. I downloaded the xview dataset and found the error "KeyError: "Dataset'xview_semantic_damage_quad_train' is not registered!" when I ran the code. I would like to ask how to register the dataset and use xview data Set to run through the code.
